credit.max.limit=10
domain.client.service.implementation=one
domain.pagamento.service.implementation=one
domain.credito.service.implementation=one
domain.prestacao.service.implementation=one
domain.producto.service.implementation
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
your.property.name=name
server.port=8080
